"""Create models User Character Room

Revision ID: 82c44154ec5e
Revises: 
Create Date: 2024-02-08 22:24:41.911635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c44154ec5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=255), nullable=False),
    sa.Column('age_childfree', sa.String(length=255), nullable=False),
    sa.Column('Physique', sa.String(length=255), nullable=False),
    sa.Column('profession', sa.String(length=255), nullable=False),
    sa.Column('health', sa.String(length=255), nullable=False),
    sa.Column('hobbies', sa.String(length=255), nullable=False),
    sa.Column('phobia', sa.String(length=255), nullable=False),
    sa.Column('character_trait', sa.String(length=255), nullable=False),
    sa.Column('luggage', sa.String(length=255), nullable=False),
    sa.Column('add_information', sa.String(length=255), nullable=False),
    sa.Column('card_1', sa.String(length=255), nullable=False),
    sa.Column('card_2', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('Private', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('room')
    op.drop_table('character')
    # ### end Alembic commands ###
